name: flutter_clean_architeture

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  test: ^1.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
   -  .env


